server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://121.41.122.244:3306/defect_detection?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: klxh
    password: cy414ljh212,,,


#七牛云配置
qiniu:
  #自己账户的ak sk
  accessKey: ewdO9r31jfwxrbvm8u07jt5NykA-jooTgp3aaivG
  secretKey: -TVsEzH2Kt0IWz-8qXkpK2MoldhfmtGkHAXfQbKa
  #存储空间名
  bucket: guosai
  # 自己的存储空间域名
  cdnProfile: r9g4tg8z7.hd-bkt.clouddn.com
  #采用的协议 http:// 还是 https://  个人此空间由于没配域名 采用的是http协议  http://qa7oc48w0.bkt.clouddn.com/logo
  protocol: http://


